---
- hosts: all
  name: install ai server
  become: yes
  vars:
    webui_port: 80
    api_port: 8888
    packages:
      - python3
      - python3-venv
      - python3-pip
      - git
      - curl
      - ffmpeg
      - libsm6
      - libxext6
    venv_path: /root/open-webui-venv
    service_name: open-webui
    user: root
    exec_command: "{{ venv_path }}/bin/open-webui serve --port {{ webui_port }} "
    key_file: authorized_keys.vault

  tasks:
    - name: Copy private key to remote server
      copy:
        src: "{{ key_file }}"
        dest: /root/.ssh/authorized_keys
        mode: 0600

    - name: change term env
      copy:
        dest: /etc/profile.d/terminal.sh
        content: |
          TERM=xterm
          export TERM

    - name: apt update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: install pkgs
      apt:
        name: "{{ packages }}"
        state: present

    - name: install ollama
      raw: curl -fsSL https://ollama.com/install.sh | sh

    - name: Enable and start ollama service
      systemd:
        name: ollama
        enabled: yes
        state: started

    - name: run model
      shell: ollama run deepseek-r1:7b >/dev/null 2>&1 &
      async: 10
      poll: 0

    - name: pull other model
      shell: ollama pull {{ item }}  >/dev/null 2>&1 &
      loop:
        - smollm2:latest
        - granite3-moe:latest
        - llama3.2:latest
        - smollm2:latest
        - mistral-nemo:latest
        - dolphin-phi:latest
      async: 10
      poll: 0

    - name: install pkgs
      apt:
        name: nginx
        state: present
      notify: stop nginx  

    - name: Create a Python virtual environment
      command: python3 -m venv "{{ venv_path }}"
      args:
        creates: "{{ venv_path }}"

    - name: Install Open-WebUI inside the virtual environment
      command: "{{ venv_path }}/bin/pip install open-webui -U"

    - name: Create systemd service file for Open-WebUI
      copy:
        dest: "/etc/systemd/system/{{ service_name }}.service"
        content: |
          [Unit]
          Description=Open-WebUI Service
          After=network.target

          [Service]
          Type=simple
          ExecStart={{ exec_command }}
          WorkingDirectory={{ venv_path }}
          Restart=always
          User={{ user }}

          [Install]
          WantedBy=multi-user.target
      notify: Restart Open-WebUI

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Open-WebUI service
      systemd:
        name: "{{ service_name }}"
        enabled: yes
        state: started

    - name: set iptables rules
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
        action: insert
        rule_num: 1
        comment: Allow incoming traffic on specified ports only
      loop:
        - "{{ webui_port }}"
        - "{{ api_port }}"
        - 22

    - name: set iptables rules
      iptables:
        chain: INPUT
        protocol: all
        source: 127.0.0.1
        jump: ACCEPT
        action: insert
        comment: Allow incoming traffic from localhost


    - name: Allow related and established connections
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Drop all other incoming connections
      iptables:
        chain: INPUT
        policy: DROP

    - name: Create Nginx config file reverse proxy
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
            listen {{ api_port}} default_server;
            location / {
              proxy_pass http://localhost:11434;
              proxy_set_header Host localhost:11434;
            }
          }
      notify: Restart nginx

    - name: Test Nginx config
      command: nginx -t
      changed_when: false

    - name: Enable Nginx service
      systemd:
        name: nginx
        state: started
        enabled: true

  handlers:
    - name: Restart Open-WebUI
      systemd:
        name: "{{ service_name }}"
        state: restarted

    - name: Restart ollama
      systemd:
        name: ollama
        state: restarted

    - name: Restart nginx
      systemd:
        name: nginx
        state: restarted

    - name: stop nginx
      systemd:
        name: nginx
        state: stopped
