---
- hosts: all
  name: install deepseek
  tasks:
    - name: apt update
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: install pkgs
      apt: name={{ item }} state=latest
      with_items:
        - git
        - curl
        - ffmpeg
        - libsm6
        - libxext6
        - python3-pip
        - python3-venv

    - name: install ollama
      raw: curl -fsSL https://ollama.com/install.sh | sh

    - name: enable and start ollama
      service:                                                                             
        name: ollama
        state: started
        enabled: true

    - name: run modell
      shell: ollama run deepseek-r1:7b >/dev/null 2>&1 &
      async: 10
      poll: 0

    - name: Create a Python virtual environment
      command: python3 -m venv /root/open-webui-venv
      args:
        creates: /root/open-webui-venv

    - name: Install Open-WebUI inside the virtual environment
      command: /root/open-webui-venv/bin/pip install open-webui

    - name: Create systemd service file for Open-WebUI
      copy:
        dest: /etc/systemd/system/open-webui.service
        content: |
          [Unit]
          Description=Open-WebUI Service
          After=network.target

          [Service]
          Type=simple
          ExecStart=/root/open-webui-venv/bin/open-webui serve --port 80
          WorkingDirectory=/root/open-webui-venv
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start Open-WebUI service
      systemd:
        name: open-webui
        enabled: yes
        state: started
